# Generated by Django 2.2.2 on 2019-06-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='error_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('level', models.CharField(max_length=40)),
                ('pid', models.CharField(max_length=15)),
                ('tid', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=100000)),
                ('client', models.CharField(max_length=50)),
                ('request', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='LogsHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remoteAddr', models.CharField(max_length=100)),
                ('remoteUser', models.CharField(max_length=10000)),
                ('timeLocal', models.DateTimeField()),
                ('request', models.CharField(max_length=10000)),
                ('status', models.CharField(max_length=100)),
                ('bodyBytesSent', models.CharField(max_length=100)),
                ('httpReferer', models.CharField(max_length=1000)),
                ('httpUserAgent', models.CharField(max_length=100000)),
                ('authorizedUser', models.BooleanField()),
            ],
        ),
    ]
